name: ${project.name}
version: ${project.version}
main: io.github.mal32.endergames.EnderGames
authors:
  - 2mal3
  - MCsharerGIT
  - lambdaphoenix
api-version: '1.21.8'
bootstrapper: io.github.mal32.endergames.PluginBootstrapper
description: ${project.description}
website: ${project.url}