name: ${project.name}
version: ${project.version}
main: io.github.mal32.endergames.EnderGames
authors:
  - 2mal3
  - MCsharerGIT
  - lambdaphoenix
api-version: '${project.api.version}'
${bootstrapperLine}
description: ${project.description}
website: ${project.url}