name: EnderGames
version: 0.3.0
main: io.github.mal32.endergames.EnderGames
authors:
  - 2mal3
  - MCsharerGIT
  - 6mal7
api-version: '1.21.4'
bootstrapper: io.github.mal32.endergames.PluginBootstrapper